//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TeknikKartOdev1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tasks
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tasks()
        {
            this.TaskStatess = new HashSet<TaskStatess>();
        }
    
        public int TaskID { get; set; }
        public string TaskName { get; set; }
        public string isAcıklama { get; set; }
        public string Notlar { get; set; }
        public Nullable<System.DateTime> BaşlangıçTarihi { get; set; }
        public Nullable<System.DateTime> PreDate { get; set; }
        public Nullable<System.DateTime> RealDate { get; set; }
        public int DurumID { get; set; }
        public int UserID { get; set; }
    
        public virtual Durumlar Durumlar { get; set; }
        public virtual Users Users { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TaskStatess> TaskStatess { get; set; }
    }
}
